### ISSUE TITLE
AWS user management token (3)

### ISSUE THREAD

**Issue by starswish2100** [starswish2100/relex-tasks#9]

**Comment by derekwu90** [comment]
AWS admin pool: https://eu-west-1.console.aws.amazon.com/cognito/users/?region=eu-west-1#/pool/eu-west-1_FSDE3eZVp/details?_k=7o01dt
user pool:  https://eu-west-1.console.aws.amazon.com/cognito/users/?region=eu-west-1#/pool/eu-west-1_MVGq7DYhc/details?_k=m4vk53****
